---
version: '3'

services:
  qinglong-bot:
    image: wenrouhao/qinglong-bot:latest
    container_name: qinglong-bot
    restart: always
    environment:
      TZ: Asia/Shanghai
      QINGLONG_URL: ${QINGLONG_URL}
      QINGLONG_CLIENT_ID: ${QINGLONG_CLIENT_ID}
      QINGLONG_CLIENT_SECRET: ${QINGLONG_CLIENT_SECRET}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_PROXY: ${TG_PROXY}
      TG_API_ROOT: ${TG_API_ROOT}
    ports:
      - '3000:3000'
